import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="sr" lang="en">
      <body className={`${inter.className} `}>
        <header className="navbar sticky top-0">
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
